In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/processed/df_final.csv")
df

,Geografía,Delitos,Año,Trimestre,Provincia,Total,Valor trimestral
0,Alaquás,Delitos Sexuales,2021,T2,Valencia,2,2.0
1,Alaquás,Delitos Sexuales,2021,T3,Valencia,2,0.0
2,Alaquás,Delitos Sexuales,2021,T4,Valencia,4,2.0
3,Alaquás,Delitos Sexuales,2022,T2,Valencia,2,2.0
4,Alaquás,Delitos Sexuales,2022,T3,Valencia,5,3.0
...,...,...,...,...,...,...,...
34057,Villaviciosa de Odón,Trafico De Drogas,2024,T3,Madrid,3,2.0
34058,Villaviciosa de Odón,Trafico De Drogas,2024,T4,Madrid,4,1.0
34059,Villaviciosa de Odón,Trafico De Drogas,2025,T1,Madrid,0,0.0
34060,Villaviciosa de Odón,Trafico De Drogas,2025,T2,Madrid,1,1.0
34061,Villaviciosa de Odón,Trafico De Drogas,2025,T3,Madrid,4,3.0

# ES IMPORTANTE NO INCLUIR 2025

In [11]:
def calculo_estadistico_delitos(df):
    df = df.copy()

    lista_delitos = ["Delitos Sexuales",
                     "Homicidios",
                     "Hurtos",
                     "Lesiones",
                     "Resto De Criminalidad Convencional",
                     "Robos Con Fuerza",
                     "Robos Con Violencia",
                     "Secuestro",
                     "Sustraccion De Vehiculos",
                     "Trafico De Drogas",
                     "Total Delitos"]
   
    df = df.groupby("Geografía")[lista_delitos].mean()

    return df.reset_index()

media_delitos = calculo_estadistico_delitos(df)
media_delitos

KeyError: "Columns not found: 'Trafico De Drogas', 'Robos Con Violencia', 'Hurtos', 'Total Delitos', 'Delitos Sexuales', 'Secuestro', 'Robos Con Fuerza', 'Lesiones', 'Sustraccion De Vehiculos', 'Resto De Criminalidad Convencional', 'Homicidios'"

In [ ]:
df_madrid_p = pd.read_csv('../data/raw/Poblacion/poblacion-madrid.csv', sep=';', encoding='latin1')
df_barcelona_p = pd.read_csv('../data/raw/Poblacion/poblacion-Barcelona.csv', sep=';', encoding='latin1')
df_valencia_p = pd.read_csv('../data/raw/Poblacion/poblacion-valencia.csv', sep=';', encoding='latin1')

In [ ]:
df_poblacion_total = pd.concat([df_madrid_p, df_barcelona_p, df_valencia_p])
df_poblacion_total

       Sexo         Municipios  Periodo Total
0     Total  28001 Acebeda, La     2025    70
1     Total  28001 Acebeda, La     2024    68
2     Total  28001 Acebeda, La     2023    67
3     Total  28001 Acebeda, La     2022    62
4     Total  28001 Acebeda, La     2021    55
...     ...                ...      ...   ...
2665  Total        46263 Zarra     2020   346
2666  Total        46263 Zarra     2019   359
2667  Total        46263 Zarra     2018   365
2668  Total        46263 Zarra     2017   381
2669  Total        46263 Zarra     2016   440

[7590 rows x 4 columns]