In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../data/processed/df_final.csv")
df

,Geografía,Año,Provincia,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos
0,Alaquàs,2021,Valencia,4,1,205,8,0,100,14,0,10,8,350
1,Alaquàs,2022,Valencia,5,0,240,14,0,99,21,0,16,7,402
2,Alaquàs,2023,Valencia,13,0,178,9,0,60,35,1,8,7,311
3,Alaquàs,2024,Valencia,9,2,188,9,0,77,22,0,12,12,331
4,Alboraia / Alboraya,2021,Valencia,3,0,391,4,0,86,32,0,16,3,535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,Villanueva de la Cañada,2024,Madrid,12,0,231,15,0,101,15,0,2,2,378
772,Villaviciosa de Odón,2021,Madrid,15,0,274,13,0,173,53,0,6,3,537
773,Villaviciosa de Odón,2022,Madrid,19,0,320,8,0,182,49,0,8,4,590
774,Villaviciosa de Odón,2023,Madrid,11,0,301,17,0,234,37,0,7,6,613
775,Villaviciosa de Odón,2024,Madrid,10,0,267,20,0,175,22,0,8,4,506

# ES IMPORTANTE NO INCLUIR 2025

In [8]:
def calculo_estadistico_delitos(df):
    df = df.copy()

    lista_delitos = ["Delitos Sexuales",
                     "Homicidios",
                     "Hurtos",
                     "Lesiones",
                     "Resto De Criminalidad Convencional",
                     "Robos Con Fuerza",
                     "Robos Con Violencia",
                     "Secuestro",
                     "Sustraccion De Vehiculos",
                     "Trafico De Drogas",
                     "Total Delitos"]
   
    df = df.groupby("Geografía")[lista_delitos].mean()

    return df.reset_index()

media_delitos = calculo_estadistico_delitos(df)
media_delitos

,Geografía,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos
0,Alaquàs,7.750000,0.750000,202.750000,10.000000,0.000000,84.000000,23.000000,0.250000,11.500000,8.500000,348.500000
1,Alboraia / Alboraya,7.750000,0.000000,519.500000,10.000000,0.000000,139.750000,36.000000,0.000000,22.500000,5.250000,740.750000
2,Alcalá de Henares,54.777778,5.888889,2499.444444,53.333333,174.000000,477.888889,195.111111,0.222222,203.333333,43.222222,3707.222222
3,Alcobendas,41.333333,1.777778,1310.333333,30.666667,73.111111,339.888889,92.555556,0.000000,183.444444,28.444444,2101.555556
4,Alcorcón,33.111111,2.555556,2326.777778,29.555556,92.777778,356.444444,203.777778,0.444444,128.444444,28.555556,3202.444444
...,...,...,...,...,...,...,...,...,...,...,...,...
111,Vilassar de Mar,7.500000,0.250000,130.250000,4.000000,0.000000,86.500000,31.250000,0.000000,12.250000,1.750000,273.750000
112,Villanueva de la Cañada,12.750000,0.250000,272.500000,9.750000,0.000000,116.500000,17.000000,0.000000,4.250000,3.750000,436.750000
113,Villaviciosa de Odón,13.750000,0.000000,290.500000,14.500000,0.000000,191.000000,40.250000,0.000000,7.250000,4.250000,561.500000
114,Xirivella,13.250000,0.750000,299.750000,14.250000,0.000000,78.000000,20.000000,0.000000,13.000000,3.750000,442.750000
115,Xàtiva,14.000000,0.750000,315.500000,17.250000,0.000000,148.250000,13.250000,0.000000,16.000000,6.000000,531.000000